spring:
  application:
    name: restapi_ex
  datasource:
    url: jdbc:h2:~/test
    driver-class-name: org.h2.Driver
    username: sa
    password: 0000
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
